spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/ds_sns?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    minimum-idle: 10
    maximum-pool-size: 10
    idle-timeout: 30000
    connection-timeout: 10000
    validation-timeout: 10000
    max-lifetime: 30000
    connection-test-query: SELECT 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        # jpql 쿼리를 보는 설정. mysql 쿼리를 확실히 보려면 끄는게 좋음.
        use_sql_comments: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
  data:
    redis:
      host: localhost
      port: 6382
      password: 1234

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
          block:
            ms: 90000
        retry:
          backoff:
            ms: 1000

    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.hibernate.SQL: DEBUG
    #    org.springframework: DEBUG
    org.springframework.cache: TRACE
    #    org.springframework.data.redis: DEBUG
    #    com.github.benmanes.caffeine.cache: DEBUG
    org.springframework.jdbc: DEBUG

  flyway:
    enabled: true
    locations: classpath:db/migration

#p6spy:
#  detail: false
#
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

server:
  port: 8203
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

springdoc:
  swagger-ui:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml